@url_dev=http://localhost:3000/v1/api


###Signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop Tips",
    "email": "shoptips8@gmail.com",
    "password": "abc123"
}