@url_dev=http://localhost:3000/v1/api


###Signup
POST {{url_dev}}/shop/signupeee
Content-Type: application/jsoneeee

{
    "name": "Shop Tips",
    "email": "shoptips1@gmail.com",
    "password": "abc123"
}